### ISSUE TITLE
Progression block

### ISSUE THREAD

**Issue by erdanilevicius** [adamico/mechanical-mastery-plus#102]
No way to get secondary materials like: tin, zinc, nickel etc... 
ATM having no way to get tin is a progression block in chapter 1, it makes impossible to craft Machine frame(from thermal series), and make other alloys

**Comment by sanyaysan** [comment]
The ores are all in the Admin Shop, it says so in the quest i think

**Comment by erdanilevicius** [comment]
Oh, lol thought that I explored everything and couldn't find it. Thanks !
