### ISSUE TITLE
Interaction Trying to connect Hyperbox and Pretty Pipes

### ISSUE THREAD

**Issue by KrakenOnHead** [adamico/mechanical-mastery-plus#107]
Trying to connect a pretty pipes Pipe to the outside of a Hyperbox caused the chunk to get messed up and does not work in general. The pipe gets used but doesnt get placed and upon reloading the previously placed pipes are back in your inventory.

**Comment by adamico** [comment]
Unfortunately pretty pipes don't seem to use ForgeCapabilities which is a necessary requisite to work with hyperbox.

The solution is using a hopper or other compatible blocks inbetween the non working ones and the hyperbox.

Commoble/hyperbox#12

**Comment by KrakenOnHead** [comment]
https://crashy.net/9072dde6-dee9-4c78-b040-8c89623ab639

**Comment by KrakenOnHead** [comment]
https://mclo.gs/bgbFnQu

**Comment by adamico** [comment]
Opened issues on Hyperbox and Pretty Pipes github

Commoble/hyperbox#17
Ellpeck/PrettyPipes#193
