### ISSUE TITLE
Too tedious recipe for Mekanism Steel Casing

### ISSUE THREAD

**Issue by EricBuist** [adamico/mechanical-mastery-plus#118]
**Describe the bug**
The steel casing recipe requires too much stuff that will be very tedious to come by. The 60 blocks of lead means 540 ingots, which is more than 8 stacks. Crafting 38 blocks of steel will also be extremely time consuming. Thermal machines such as pulverizers are too slow to perform this crafting efficiently. This can of blocks progression into chapter 3 without cheating in the steel casing, until they can be purchased with the T3 permit later on. Up to this point I was able to progress smoothly in the pack, but that is a major roadblock for me.

**To Reproduce**
1. Look for recipe for steel casing.
2. Look at number of blocks of lead, steel and osmium.
3. Process one stack of raw lead in a pulverizer and enjoy waiting forever.
4. Be prepared to wait or craft 8+ pulverizers, without any crafting automation like Refined Storage or Applied Energistics to help along the way.
5. error:

**Expected behavior**
There should be a reasonable recipe for steel casing. Using a regular mechanical essence could be a way to gate steel casing to chapter 3.

**Comment by sanyaysan** [comment]
At first I felt like this too, but after actually doing it, I disagree with you . The small challenge to get all the steel and lead makes it much more worth it. The craft gives you 4 frames iirc, which is enough to get you to the next chapter to buy casings.
I did all of this using 2 pulverizers with integral components and 1 millstone + mixer. The setup wasn't beautiful, but it worked and got me to the permit that unlocks buying the casing.
Just try and speedrun the next tier and permit. Later, you can automate everything.

**Comment by sarim** [comment]
> which is enough to get you to the next chapter to buy casings

If the crafting is so much hassle that you just do it once and always buy from market, then that kinda validates the point that craft is unnecessarily complex :P

**Comment by sanyaysan** [comment]
Maybe modifying the recipe to be a 3x3x3 would be a good middle ground?

**Comment by adamico** [comment]
Yes, there's definitely something to change here. And I agree with @sarim about the need to do it only once (unless you don't want to spend money on steel casing and just automate the compact crafting recipe).
I'll change the recipe to 3x3 for now and then we'll see how it goes.
