### ISSUE TITLE
Recipe conflicts can only be resolved with vanilla crafting table

### ISSUE THREAD

**Issue by swoolcock** [adamico/mechanical-mastery-plus#119]
Most notably the recipe conflict between AE2 energy acceptor and Iron Chests copper chest upgrade.

Trying to do this in a crafting station or with the AE2 crafting terminal usually gives the chest upgrade, but it seems to be somewhat random what you get.

I'm not sure if you can do anything about the recipe selection button, but it might be a good idea to go through the crafting recipes and remove any notable conflicts.

Problem occurs on both 1.1.4 and 1.1.5, not sure about older versions.

**Comment by PrototypeTrousers** [comment]
https://www.curseforge.com/minecraft/mc-mods/polymorphic-energistics was invented a week ago
