### ISSUE TITLE
Cannot create/enter world - game crashes (error code 6)

### ISSUE THREAD

**Issue by Cooperwilton1070** [adamico/mechanical-mastery-plus#124]
**Describe the bug**
First time ive installed the pack. Going through the create new world UI, clicking the final create new world button warns of experimental features then client crashes

**To Reproduce**
1. Start curseforge
2. Install or Start Mechanical Mastery Plus 1.16
3. Create or Load World
4. do the action that causes the bug
5. error:

**Expected behavior**
Expected to be able to create and enter world

**Screenshots**

**Logs**
crash log https://pastebin.com/eE8fAcWG
Curseforge log PB 1 https://pastebin.com/epS7SujX
Curseforge log PB 2 https://pastebin.com/GM33415b

**Comment by adamico** [comment]
Which loader are you using? Curseforge launcher on osx?
Could you repost the crashlog on https://mclo.gs/? please

**Comment by Cooperwilton1070** [comment]
Yep, curseforge on OSX, M1 arch if that matters…

mclogs crashlog - https://mclo.gs/L4ZC90s

**Comment by adamico** [comment]
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3325#issuecomment-1544401161

try downgrading your jdk to 17.0.6, it's a java specific bug for osx
