### ISSUE TITLE
[🐞] Crash/Visual glitch/Recipe not working etc.

### ISSUE THREAD

**Issue by DiscoverProgramming** [adamico/mechanical-mastery-plus#126]
### Which OS are you using?

WINDOWS

### Which Launcher?

CurseForge Launcher

### Describe the bug

It is currently **impossible** to get the energy acceptor, as you cannot get the gray dye required to make the stained glass that is needed to make the energy acceptor.

### To reproduce

# Steps to reproduce the behavior:

1. Load Launcher
2. Run the mod(v1.1.6) in Minecraft version 1.19.2
3. (Nothing else, description provides info)

### Expected behavior

For the player to be able to get gray dye.

### Logs

(read description)

**Comment by sarim** [comment]
you can get grey dye from white + black. white from bonemeal. black from charcoal.

**Comment by DiscoverProgramming** [comment]
I don't see any recipe for charcoal to be converted to black dye.

**Comment by sarim** [comment]
its not a crafting recipe, its a squeezer recipe.

**Comment by DiscoverProgramming** [comment]
Alright, thanks! It works.
