### ISSUE TITLE
Rebalancing fission casing

### ISSUE THREAD

**Issue by sanyaysan** [adamico/mechanical-mastery-plus#128]
**Is your feature request related to a problem? Please describe.**
A minimum size mekanism reactor takes 32 fission casing (including reactor port 2x). This takes 

**Describe the solution you'd like**
A solution to this problem would be upping the result of 1 craft to 6 or 8. This will result in significantly cheaper casings. 900 lead ingots for 1 reactor.

**Describe alternatives you've considered**
Waiting a long long time for just lead ingots

**Additional context**
![fission_casing](https://github.com/adamico/mechanical-mastery-plus/assets/58048019/7e27d7d7-6f55-49bf-bb50-e4a4dbfeb7d5)

**Comment by sanyaysan** [comment]
Same goes for the turbine casings. Minimum size requires 64 casing (including valves and vents) = 416 steel casing.
8.1K * 416 = 3.4M, which can be acceptable but adding the cost of osmium and improved essence it becomes a bit much i reckon.

**Comment by adamico** [comment]
8 per craft looks too easy, maybe 6?

![image](https://github.com/adamico/mechanical-mastery-plus/assets/81559/a780363e-d0f9-413b-a681-56063cabc4a4)

**Comment by adamico** [comment]
hmm, finally it's ok to pump all recipe outputs to x8, turbine casings are still expensive but easy to obtain at the time you will need a bigger setup
