### ISSUE TITLE
[🐞] Missing endstone recipe

### ISSUE THREAD

**Issue by sanyaysan** [adamico/mechanical-mastery-plus#141]
### Describe the bug

There currently is no way to obtain end stone, making some recipes uncraftable.
This includes modular routers sender module mk 3, some backpacks, but also inhibits spawning shulkers using the rftools spawner.

### To reproduce

Lookup recipe for endstone --> none found

### Expected behavior

Add a recipe for endstone, maybe bulk haunting or include it in the shop.

**Comment by sanyaysan** [comment]
The spawner currently seems overlooked. Find out more on the [wiki](https://ftbwiki.org/Spawner)

**Comment by adamico** [comment]
@sanyaysan  I have an idea about generating End Stone in a cool way (and instructing for me). In which questline chapter do you think End Stone should be obtainable?

**Comment by sanyaysan** [comment]
Hmm, since you dont really need it for other progression besides the rftools spawner, I think at the beginning of ch4 would be fine. You still need chorus anyway, so before that wouldn't be of much use.

**Comment by adamico** [comment]
I managed to implement my initial idea:

![endstone](https://github.com/adamico/mechanical-mastery-plus/assets/81559/35c4f856-76bd-4e66-b9fe-54db7d17dbc0)

I was thinking about selling a spawn egg in the shop with permit tier 4.

**Comment by sarim** [comment]
All spawner should be at similar progression level right? Industrial Foregoing mob imprisonment tool and Mob duplicator. Mob Grinding tool entity spawner...

**Comment by adamico** [comment]
rftools spawner needs some love (or hate?) for sure, but maybe you're right, I need to put all mob farm blocks and items at the same progression level.
BTW, the gif above doesn't reflect the current implementation... too easy!
