### ISSUE TITLE
[🐞] Missing Create press recipe for constantan plates

### ISSUE THREAD

**Issue by juh9870** [adamico/mechanical-mastery-plus#142]
### Which OS are you using?

LINUX

### Which Launcher?

Prism

### Describe the bug

All metals have plate pressing recipe in a Create press, but Constantan seems to be an exception for some reason

### To reproduce

1. Make a Create press
2. Try to press Constantan ingot

### Expected behavior

Ingot should be pressed

### Logs

Not applicable

**Comment by adamico** [comment]
@juh9870 I have an idea about generating End Stone in a cool way (and instructing for me). In which questline chapter do you think End Stone should be obtainable?
