### ISSUE TITLE
[🐞] Crafting Interfaces ignore blocking mode when distributed

### ISSUE THREAD

**Issue by juh9870** [adamico/mechanical-mastery-plus#144]
### Which OS are you using?

LINUX

### Which Launcher?

Prism

### Describe the bug

When a recipe is distributed between multiple machines (Thermal Expansion Induction Smelter in my case) using Crafting Interface from Integrated Crafting, interfaces will try to insert multiple recipes at once into each machine, even when having blocking mode enabled.

### To reproduce

1. Place multiple Thermal Expansion Induction Smelters with this configutration
  ![image](https://github.com/adamico/mechanical-mastery-plus/assets/15922601/8ef44b7a-8ff4-4709-9654-a1e93d7427b2)
2. Attach Crafting interface to each of them from the right side, two recipes into each of them (for example, invar and bronze).
3. Queue crafting so each machine would need to do at least two crafting cycles
4. Observe that after one or more crafting cycles, each machine will receive multiple recipe inputs and get clogged.

### Expected behavior

Each machine should only receive input for one recipe

### Logs

https://mclo.gs/v5rRdOK

**Comment by adamico** [comment]
After a long discussion and thorough testing I've come to the conclusion this is working as intended, annoying but working.
