### ISSUE TITLE
[Feature] LaserIO gate or nerf

### ISSUE THREAD

**Issue by adamico** [adamico/mechanical-mastery-plus#21]
[Laser IO](https://www.curseforge.com/minecraft/mc-mods/laserio "Laser IO")

**Comment by sanyaysan** [comment]
Maybe adding a mechanical essence to the recipe or at leat making the energy cards more expensive

**Comment by sarim** [comment]
I think its okey not being nerfed or gated. Not everything need to be locked under grind.

**Comment by adamico** [comment]
not under grind but under one of the essences could be ok

**Comment by sanyaysan** [comment]
Hmm, maybe the regular essence would be better for the chips, but adding the advanced one to the wrench would be an option. That way you can still use it for automation, but its locked until start of chapter 3.
