### ISSUE TITLE
Main Menu Resolution

### ISSUE THREAD

**Issue by WyFryMU** [adamico/mechanical-mastery-plus#69]
Kinda self explanatory, using v1.1 or v1.2 (not sure about others), all the buttons are off screen when not fullscreen or maximized. Not a high priority, but thought still worth reporting.
Smaller window, the buttons are off screen.
![image](https://github.com/adamico/mechanical-mastery-plus/assets/47251130/dcabe589-e70b-49b0-a24e-8413f9a9cf2c)
Fullscreen looks normal
![image](https://github.com/adamico/mechanical-mastery-plus/assets/47251130/c6d74982-6033-4e8b-b49c-06e4e0de6608)

**Comment by adamico** [comment]
it's supposed to look like this:
![full title screen](https://github.com/adamico/mechanical-mastery-plus/assets/81559/5c51aaa0-db58-478c-a1c1-7f93bc492e08)

I'll fix this right away
