### ISSUE TITLE
Shadow essence bug

### ISSUE THREAD

**Issue by danilo358** [adamico/mechanical-mastery-plus#87]
When u pick the shadow essence on a bucket the game see that how another liquid and we cant filter it for automate the things, anything accept the bucket, the way i found is put on ground and some machine collect it for me

**Comment by adamico** [comment]
Do you mean, when you try filtering the mixer for the recipe of shadow essence with a bucket of shadow essence it doesn't work?
Why do you want to filter it? There's no need to filter it because there's no other recipe requiring two of the three ingredients.
